### ISSUE TITLE
Random generation problem

### ISSUE THREAD

**Issue by older-fox** [adiliqbl/mongoose-nanoid#10]
Is there any way to specify the characters that can be used in random string generation?

**Comment by older-fox** [comment]
In nanoid, you can use customAlphabet()  to specify, but I don't know how to implement it in mongoose-nanoid

**Comment by adiliqbl** [comment]
You can pass params to the plugin instead of length & call `customAlphabet` on nanoid. I'm not actively working on this plugin but if you are willing to make some changes, I am more than happy to merge them.

Please have a look at the mongoose docs on how to modify `index.js`
https://mongoosejs.com/docs/plugins.html

**Comment by adiliqbl** [comment]
@older-fox `v2.1.0` now has support for custom alphabets. You can either pass length or options to plugin.

```
mongoose.plugin(require('mongoose-nanoid'), size)
--OR--
mongoose.plugin(require('mongoose-nanoid'), { length: size, alphabets: "abcd@" })
```
